weather-report:
  api: https://www.ilmateenistus.ee

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web: INFO

feign:
  client:
    config:
      default:
        loggerLevel: BASIC
